### ISSUE TITLE
Alder Lake N (N100) IntelGopDriver.efi

### ISSUE THREAD

**Issue by ousui** [cmd2001/build-edk2-gvtd#1]
UBU 提取，version Unknow
bios 来源 零客官方 EQ12

CPU 包括 N50 N95 N97 N100 N200 N300 N305

受环境所限，我这不太好下 转 rom 工具，只提取了 efi，包含 vbt，不知道为何 vbt 有三个

[IntelGopDriver.zip](https://github.com/cmd2001/build-edk2-gvtd/files/12889110/IntelGopDriver.zip)
![image](https://github.com/cmd2001/build-edk2-gvtd/assets/2839512/981ee6b5-059e-4f40-ad4f-3c1fb5da192d)

**Comment by cmd2001** [comment]
Thanks for your contribution.

However, I need `GOP` in `.efi` format instead of `.bin` as I do not want to convert its format.

So I managed to get `Unknown_AlderLakeN.efi` from [ASRock N100M](https://www.asrock.com/mb/Intel/N100M/index.asp#BIOS), which is also a motherboard with Intel® Quad-Core Processor N100 and the `efi` should be compatible with EQ12.

The updated `AIO.rom` and another OpROMbuilt for each platform will appear in next release.

As for the `Vbt`, it does not matter as the PlatformGOPPolicy from Intel's latest codebase will automatically extract it at runtime, which means we do not have to embed them into `OVMF` or `OpROM`.

**Comment by ousui** [comment]
> Thanks for your contribution.
> 
> However, I need `GOP` in `.efi` format instead of `.bin` as I do not want to convert its format.
> 
> So I managed to get `Unknown_AlderLakeN.efi` from [ASRock N100M](https://www.asrock.com/mb/Intel/N100M/index.asp#BIOS), which is also a motherboard with Intel® Quad-Core Processor N100 and the `efi` should be compatible with EQ12.
> 
> The updated `AIO.rom` and another OpROMbuilt for each platform will appear in next release.
> 
> As for the `Vbt`, it does not matter as the PlatformGOPPolicy from Intel's latest codebase will automatically extract it at runtime, which means we do not have to embed them into `OVMF` or `OpROM`.

嗯，我也是各种受限（尤其是网络），没法从 bin 转到 efi。
不过有了就好了，我再试一下。
