### ISSUE TITLE
生成的OVMF_CODE_4M.fd文件，里面没有IntelGOPDriver

### ISSUE THREAD

**Issue by kimown** [cmd2001/build-edk2-gvtd#2]
这是放入gop目录里面IntelGopDriver.efi文件。
[IntelGopDriver.efi.zip](https://github.com/cmd2001/build-edk2-gvtd/files/12908342/IntelGopDriver.efi.zip)

这是执行命令后，product目录生成的4个文件。
[b660.zip](https://github.com/cmd2001/build-edk2-gvtd/files/12908348/b660.zip)

使用mmtool 5.0.0.7打开b660.zip中的OVMF_CODE_4M.fd文件，发现里面没有IntelGOPDriver和PlatformGOPPolicy

**Comment by cmd2001** [comment]
This is due to a typo in the [Usage](https://github.com/cmd2001/build-edk2-gvtd?tab=readme-ov-file#usage) section of `readme.md`.

In fact, you should use `sudo bash ./build_ovmf.sh` instead of `sudo sh ./build_ovmf.sh`, otherwise, the build script will not work.

After executing the appropriate building command, `IgdAssignmentDxe` and `PlatformGOPPolicy` should appear after `VirtioSerialDxe` like in the following picture.

Remind that `IntelGOPDriver` would NEVER appear in `OVMF_CODE_4M.fd` or `OVMF_CODE_4M.secboot.fd` as it has been moved to external OpRom like `B660.rom`.

<img width="551" alt="" src="https://github.com/cmd2001/build-edk2-gvtd/assets/25078724/2188ed3b-bbe6-4bb7-8d4d-84a8a05f5ff5">
